name: MVAD
channels:
    - pytorch
    - defaults
    - conda-forge
dependencies:
    - python=3.9
    - pytorch=1.12.1
    - torchvision=0.13.1
    - cudatoolkit=11.6
    - pip:
        - omegaconf==2.2.3
        - timm==0.9.10 
        - decord==0.6.0
        - opencv-python==4.8.1.78
        - scipy==1.10.1
        - pytorch-lightning==2.1.3
        - einops==0.7.0
        - wandb==0.16.2
        - pudb



# conda create -n artefactVQA python=3.9
# conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.6 -c pytorch -c conda-forge
# pip install omegaconf==2.2.3
# pip install timm==0.9.10 
# pip install decord==0.6.0
# pip install opencv-python==4.8.1.78
# pip install scipy==1.10.1
# pip install pytorch-lightning==2.1.3
# pip install einops==0.7.0
# pip install wandb==0.16.2
# pip install pudb
# conda install -c conda-forge pysoundfile (windows-only)